---
version: '3.2'
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    volumes:
      - /home/apex/docker/plex/library:/config
      - /mnt/nas/tv:/data/tvshows
      - /mnt/nas/movies:/data/movies
      - /home/apex/docker/plex/transcode:/transcode
    network_mode: host
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Amsterdam
      - VERSION=public
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    volumes:
      - /home/apex/docker/sonarr:/config:rw
      - /mnt/nas/tv:/tv:rw
      - /mnt/nas/downloads/complete:/downloads:rw
    ports:
      - 1002:8989
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Amsterdam
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    volumes:
      - /home/apex/docker/radarr:/config
      - /mnt/nas/movies:/movies
      - /mnt/nas/downloads/complete:/downloads
    ports:
      - 1003:7878
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Amsterdam
    restart:
      always
  transmission:
    image: linuxserver/transmission
    volumes:
      - /mnt/nas/downloads/complete:/downloads
      - /home/apex/docker/transmission/.config:/etc/transmission-daemon
      - /home/apex/docker/transmission/:/var/lib/transmission-daemon
    ports:
      - 51413:51413
      - 1005:9091
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Amsterdam
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    restart: always
    volumes:
      - /home/apex/docker/jackett/config:/config
      - /mnt/nas/downloads/complete:/downloads
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Amsterdam
    ports:
      - 1007:9117
